### ISSUE TITLE
Non-functional on Windows 10

### ISSUE THREAD

**Issue by TheBambino** [miki4920/TerrariaFishingBot#1]
Has this been tested on Windows 10? 

I successfully installed all the requirements and am able to run the program, but it doesn't seem click upon sound. Instead, it clicks at a given duration.

**Comment by mikolajg-tt** [comment]
I have looked into it, and it was an issue with the library responsible for detecting sound. Try a new release. Just make sure to install the new dependencies and that your output sound device is set to be a default one.

If you have any more issues, feel free to post them.
