### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by Noopig** [miki4920/TerrariaFishingBot#2]
I installed py3.9 and pynput+wxpython.But when running the ".py "file in Idle, it says" ModuleNotFoundError: No module named 'soundcard' ". How do I fix it

**Comment by mikolajg-tt** [comment]
Install the module. It's in the requirements.
Link to it: https://pypi.org/project/SoundCard/
That should make it work.

**Comment by Noopig** [comment]
thank
